apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yctzk7t7d-nodejs
  janus-idp.io/tekton: yctzk7t7d-nodejs
  backstage.io/kubernetes-id: yctzk7t7d-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yctzk7t7d-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
